### ISSUE TITLE
Index content-links

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/webarchive-discovery#3]
Links to JavaScript, CSS and inline images should be indexed on par with outgoing (`a href`) links. This opens up for efficient statistics calculation on resource use.

**Comment by thomasegense** [comment]
Implementing images in new solr field.
css/javascript are too fuzzy to extract (@import. recursive references, inline css/js in html pages)

**Comment by thomasegense** [comment]
Image links implemented. new solr field and new config property to activate it
