### ISSUE TITLE
content_type_norm should be definable

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/webarchive-discovery#6]
We should extract a list of mime-types from the existing index and use that for building an updated version of the content_type_norm-field. Alternatively someone else might have done the work for us, which we can the incorporate.

**Comment by thomasegense** [comment]
Closing.. It seems to be doing a good job already. Javascript is detected as text, but there is really no (easy) method to test if text is javascript. Tike detects is at text. Server says it is text/plain...
